<a href="https://colab.research.google.com/github/Raman-Raje/colab_notebooks/blob/master/contant_weights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

import keras
from keras.models import Sequential,Model
from keras.layers import Dense

In [3]:
model = Sequential()
model.add(Dense(2,name="w_0",activation="relu"))
model.add(Dense(1,name="w_1",activation="relu"))
model.compile(loss= "mean_squared_error")

In [9]:
X,Y = np.random.randint(0,10,(10,2)),np.random.randint(0,10,(10,1))
model.fit(X,Y)

1/1 [==============================] - 1s 564ms/step - loss: 31.2812


In [10]:
w_0 = np.ones((2,2),dtype="float32")
w_1 = np.ones((2,1),dtype="float32")

wb_1=np.zeros((1,),dtype="float32")
wb_0=np.zeros((2,),dtype="float32") 


In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
w_0 (Dense)                  (None, 2)                 6         
_________________________________________________________________
w_1 (Dense)                  (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [17]:
ww_0 = []
ww_0.append(w_0)
ww_0.append(wb_0)
model.layers[0].set_weights(ww_0)

ww_1 = []
ww_1.append(w_1)
ww_1.append(wb_1)
model.layers[1].set_weights(ww_1)

In [19]:
X,Y = np.random.randint(0,10,(10,2)),np.random.randint(0,10,(10,1))
for i in range(5):
  print("++++++++weights+++++++++++")
  model.fit(X,Y,epochs=1)
  for layer in model.layers:
    print(np.round(layer.get_weights()[0],decimals=4))

++++++++weights+++++++++++
1/1 [==============================] - 0s 4ms/step - loss: 174.9777
[[0.9931 0.9931]
 [0.9934 0.9934]]
[[0.9932]
 [0.9932]]
++++++++weights+++++++++++
1/1 [==============================] - 0s 3ms/step - loss: 174.1621
[[0.9925 0.9925]
 [0.9924 0.9924]]
[[0.9924]
 [0.9924]]
++++++++weights+++++++++++
1/1 [==============================] - 0s 3ms/step - loss: 173.3413
[[0.9918 0.9918]
 [0.9914 0.9914]]
[[0.9916]
 [0.9916]]
++++++++weights+++++++++++
1/1 [==============================] - 0s 3ms/step - loss: 172.5158
[[0.9911 0.9911]
 [0.9904 0.9904]]
[[0.9907]
 [0.9907]]
++++++++weights+++++++++++
1/1 [==============================] - 0s 3ms/step - loss: 171.6859
[[0.9904 0.9904]
 [0.9894 0.9894]]
[[0.9898]
 [0.9898]]


# Observations:
1. Hidden layers will lern the same thing as all the inputs from 1st layes wil be same.
2. weights at each input will only change, but the weights at deep inside n/w will change linearly.
3. It wil be a linear model.